
/*
 * ESP32 Standalone Fall Detection (MobileNetV2)
 * Requires 'model_data.h' generated by Python script.
 */
 
#include <EloquentTinyML.h> // Library Manager: Install "EloquentTinyML"
#include <esp_camera.h>
#include "model_data.h"

#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27
#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

// MobileNet Settings
#define NUMBER_OF_INPUTS 96*96*3
#define NUMBER_OF_OUTPUTS 1
#define TENSOR_ARENA_SIZE 80 * 1024

Eloquent::TinyML::TfLite<NUMBER_OF_INPUTS, NUMBER_OF_OUTPUTS, TENSOR_ARENA_SIZE> ml;

void setup() {
  Serial.begin(115200);
  
  // Camera Init (QVGA -> Crop to 96x96 later)
  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_GRAYSCALE; // Simple grayscale for speed
  config.frame_size = FRAMESIZE_96X96; // Custom or use QVGA and crop

  esp_camera_init(&config);
  
  ml.begin(model_data);
  Serial.println("Model Loaded!");
}

void loop() {
  camera_fb_t * fb = esp_camera_fb_get();
  if (!fb) return;

  // Convert image to input array (Normalization 0-1 or Int8)
  uint8_t *input = fb->buf;
  
  // Inference
  float prediction = ml.predict(input);
  
  if (prediction > 0.5) {
     Serial.println("FALL DETECTED!");
  } else {
     Serial.println("Normal");
  }

  esp_camera_fb_return(fb);
  delay(100);
}
